
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - './**/*'
          - './*'
    jobs:
      cd:  # deploy changes to workspace 'advent_of_code_2023'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v2.3.0
        with:
          tb_deploy: false
          data_project_dir: .
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
